config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts, except: :show do
    resources :comments, except: :show
  end
  resources :friendships, only: [:index, :create] do
    put :confirm, :unfriend, :ignore, :cancel
  end
  resources :groups
  resources :join_groups do
    put 'approve/:group_id', as: :approve, to: 'join_groups#approve'
    put :remove, :leave, :cancel
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content , presence: true
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]
  include ApplicationHelper

  def index
    @comments = @post.comments.includes(:user)
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_comments_path
      flash[:notice] = "Successfully Created"
    else
      render :new
    end
  end

  def edit
    authorize @comment, :edit?, policy_class: CommentPolicy
  end

  def update
    authorize @comment, :update?, policy_class: CommentPolicy
    if @comment.update(comment_params)
      flash[:notice] = "Successfully Updated"
      redirect_to post_comments_path
    else
      render :edit
    end
  end

  def destroy
    authorize @comment, :destroy?, policy_class: CommentPolicy
    if @comment.destroy
      flash[:notice] = "Successfully Deleted"
      redirect_to post_comments_path
    end
  end

  private

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def set_post
    @post = Post.where(id: filter_post).find params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/edit.html.erb
<%= render "shared_form/navbar" %>
<div class="container" style="margin-top: 100px">
  <h3 class="text-light"><b>Edit Comment</b></h3>
  <div class="card w-100 mt-3 mb-5 shadow border-light" style="background-color: #e4ede4">
    <div class="card-body ">
      <%= form_for @comment, url: post_comment_path, method: :patch do |f| %>
        <div class="row mt-3">
          <div class="col">
            <div class="form-outline mb-4">
              <%= f.text_area :content, class: "form-control shadow-sm shadow-sm border-light", placeholder: "Write a comment...", :cols => 20, :rows => 1 %>
              <%= content_tag :p, @comment.errors.full_messages_for(:content).join(', '), class: 'text-danger' if @comment.errors.has_key?(:content) %>
            </div>
          </div>
          <div class="pt-1 text-center mb-2">
            <%= link_to 'Back', post_comments_path, class: "btn btn-warning px-5 mx-3 shadow-sm" %>
            <%= f.submit "Update", data: { confirm: 'Are you sure you want to Update?' }, class: "btn btn-success px-5 mx-3 shadow-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<%= render "shared_form/navbar" %>
<div class="container mb-5" style="margin-top: 120px">
  <%= render "shared_error/flash_error" %>
  <div class="card mt-3 shadow border-light">
    <div class="card-header shadow-sm border-light" style="background-color: #e4ede4">
      <div class="row">
        <div class="col-10">
          <h5 class="card-title mt-3" style="color:darkorange;"><%= @post.user.email %></h5>
          <%= content_tag :div, @post.created_at.to_s(:long), class: "badge bg-light text-dark shadow-sm" %>&nbsp;<%= content_tag :div, @post.genre.humanize, class: "badge bg-secondary shadow-sm" %>
        </div>
        <div class="col">
          <%= link_to posts_path, class: "nav-link" do %>
            <div class="d-flex justify-content-end mt-3" >
              <i class="fa-solid fa-chevron-left"></i>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-body shadow-sm">
      <p class="card-text mt-3 mb-3"><b></b> <%= @post.content %></p>
      <% if @post.image? %>
        <div class="overflow-hidden" style="width: 100%; aspect-ratio: 2/1">
          <%= image_tag @post.image.url, style: "object-fit: cover" %>
        </div>
      <% end %>
    </div>
    <div class="card-footer" style="background-color: #e4ede4">
      <% @comments.each do |comment| %>
        <div class="row ">
          <div class="col mt-3">
            <h6><%= comment.user.email %></h6>
          </div>
          <% if policy(comment).edit? %>
            <div class="col-8">
              <div class="col d-flex justify-content-end">
                <div class="dropend">
                  <button class="btn btn-sm" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                    <h6>...</h6>
                  </button>
                  <ul class="dropdown-menu shadow-sm border-light">
                    <%= link_to "Edit", edit_post_comment_path(@post, comment), class: "dropdown-item" %>
                    <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "dropdown-item" %>
                  </ul>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <p class="badge bg-light text-dark shadow-sm"><%= comment.content %></p>
      <% end %>
      <hr>
      <%= link_to new_post_comment_path, class: "nav-link" do %>
        <div class="form-outline mb-2 text-center">
          <%= text_field_tag :p, nil, placeholder: "Write a comment...", readonly: :true, class: "form-control shadow-sm border-light" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<%= render "shared_form/navbar" %>
<div class="container" style="margin-top: 100px">
  <h3 class="text-light"><b>Create Comment</b></h3>
  <div class="card w-100 mt-3 mb-5 shadow border-light" style="background-color: #e4ede4">
    <div class="card-body ">
      <%= form_for @comment, url: post_comments_path, method: :post do |f| %>
        <div class="row mt-3">
          <div class="col">
            <div class="form-outline mb-4">
              <%= f.text_area :content, class: "form-control shadow-sm shadow-sm border-light", placeholder: "Write a comment...", :cols => 20, :rows => 1 %>
              <%= content_tag :p, @comment.errors.full_messages_for(:content).join(', '), class: 'text-danger' if @comment.errors.has_key?(:content) %>
            </div>
          </div>
          <div class="pt-1 text-center mb-2">
            <%= link_to 'Back', post_comments_path, class: "btn btn-warning px-5 mx-3 shadow-sm" %>
            <%= f.submit "Create", data: { confirm: 'Are you sure you want to create?' }, class: "btn btn-success px-5 mx-3 shadow-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>