config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts, except: :show do
    resources :comments, except: :show
  end
  resources :friendships, only: [:index, :create] do
    put :confirm, :unfriend, :ignore, :cancel
  end
  resources :groups
  resources :join_groups do
    put 'approve/:group_id', as: :approve, to: 'join_groups#approve'
    put :remove, :leave, :cancel
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :image, :description, :privacy, presence: true
  belongs_to :user
  has_many :join_groups
  has_many :users, through: :join_groups

  enum privacy: [:visible, :hidden]
  mount_uploader :image, ImageUploader
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, except: [:index, :new, :create]

  def index
    join_groups = current_user.join_groups.where.not(state: [:removed, :ignored, :leaved, :cancelled])
    group_ids = join_groups.pluck(:group_id)
    @group_lists = Group.where.not(id: group_ids) if params[:records].blank? || params[:records] == 'group_lists'
    @requests = join_groups.pending.includes(:group) if params[:records] == 'requests'
    @joined_groups = current_user.join_groups.approved.where.not(is_owner: true).includes(:group) if params[:records] == 'joined_groups'
    @manage_groups = current_user.join_groups.approved.where.not(role: :member).includes(:group) if params[:records] == 'manage_groups'
  end

  def new
    @group = Group.new
  end

  def show
    @approvals = JoinGroup.where.not(user: current_user).where(group: @group).pending.includes(:user) if params[:records] == 'approvals'
    @members = JoinGroup.where(group: @group).approved.includes(:user) if params[:records] == 'members' || params[:records] == 'assign_role'
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save!
      join_group = JoinGroup.new(state: :approved, role: :admin, is_owner: true, user: current_user, group: @group)
      join_group.save!
      flash[:notice] = "Successfully Created"
      redirect_to groups_path(records: :manage_groups)
    else
      render :new
    end
  end

  def edit
    authorize @group, :edit?, policy_class: GroupPolicy
  end

  def update
    authorize @group, :update?, policy_class: GroupPolicy
    if @group.update(group_params)
      flash[:notice] = "Successfully Updated"
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    authorize @group, :destroy?, policy_class: GroupPolicy
    if @group.destroy
      @group.join_groups.destroy_all
      flash[:notice] = "Successfully Deleted"
    else
      flash[:alert] = "Can't delete this post!"
    end
    redirect_to groups_path(records: :manage_groups)
  end

  private

  def group_params
    params.require(:group).permit(:name, :image, :description, :privacy)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/views/groups/_form.html.erb
<div class="col">
  <div class="form-outline mb-4">
    <%= f.file_field :image, class: "form-control mt-3 mb-3 shadow-sm" %>
    <%= content_tag :p, @group.errors.full_messages_for(:image).join(', '), class: 'text-danger' if @group.errors.has_key?(:image) %>
    <%= f.text_field :name, class: "form-control mt-3 mb-3 shadow-sm", placeholder: "Name" %>
    <%= content_tag :p, @group.errors.full_messages_for(:name).join(', '), class: 'text-danger' if @group.errors.has_key?(:name) %>
    <%= f.text_area :description, class: "form-control mt-3 mb-3 shadow-sm", placeholder: "Description", :cols => 20, :rows => 1 %>
    <%= content_tag :p, @group.errors.full_messages_for(:description).join(', '), class: 'text-danger' if @group.errors.has_key?(:description) %>
    <%= f.select(:privacy, Group.privacies.keys.map { |key| [key.humanize, key] }, { :prompt => 'Privacy' }, class: "form-control form-select mt-3 mb-3 shadow-sm") %>
    <%= content_tag :p, @group.errors.full_messages_for(:privacy).join(', '), class: 'text-danger' if @group.errors.has_key?(:privacy) %>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render "shared_form/navbar" %>
<div class="container" style="margin-top: 100px">
  <h1><b>Edit Group</b></h1>
  <div class="card w-100 mt-3 mb-5 shadow border-light">
    <div class="card-body bg-light">
      <%= form_for @group, url: group_path, method: :patch do |f| %>
        <div class="row mt-3">
          <%= render "form", f: f %>
          <div class="pt-1 text-center mb-2">
            <%= link_to 'Back', groups_path, class: "btn btn-warning px-5 mx-3 shadow-sm" %>
            <%= f.submit "Update", data: { confirm: 'Are you sure you want to Update?' }, class: "btn btn-success px-5 mx-3 shadow-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<%= render "shared_form/navbar" %>
<div class="container mb-5" style="margin-top: 120px">
  <%= render "shared_error/flash_error" %>
  <div class="card shadow" style="background-color: #e4ede4">
    <div class="card-body">
      <div class="row">
        <div class="col-4 col-sm-4 col-md-3">
          <h1><b>Groups</b></h1>
        </div>
        <div class="col-8 col-sm-8 col-md-9">
          <div class="d-flex justify-content-end">
            <%= link_to "Group Lists", groups_path(records: 'group_lists'), class: "btn btn-success btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "Requests", groups_path(records: 'requests'), class: "btn btn-success btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "Joined Group", groups_path(records: 'joined_groups'), class: "btn btn-success btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "Manage Group", groups_path(records: 'manage_groups'), class: "btn btn-success btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "", new_group_path, class: "btn btn-light btn-sm mt-2 px-2 shadow-sm fa-plus", style: "font-size: min( 1.5vw, 15px)" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% @manage_groups&.each do |manage_group| %>
    <div class="card mt-3 shadow">
      <div class="card-body" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-2">
            <span class="position-absolute top-0 start-0 translate-middle badge rounded-pill text-bg-light shadow-sm" style="font-size: min( 1vw, 20px)"><%= JoinGroup.pending.where(group: manage_group.group).size %></span>
            <%= link_to group_path(manage_group.group), class: "text-decoration-none text-dark" do %>
              <%= image_tag manage_group.group.image.url, class: "img-thumbnail shadow-sm border-light", style: "width: 100%; height:100%" %>
            <% end %>
          </div>
          <div class="col-8">
            <p class="badge bg-light text-dark shadow-sm" style="font-size: min( 1.5vw, 13px)"><%= manage_group.group.privacy.humanize %></p>
            <h3 style="font-size: min( 3vw, 20px)"><b><%= manage_group.group.name %></b></h3>
            <p style="font-size: min( 2vw, 15px)"><%= manage_group.group.description %></p>
          </div>
          <div class="col-2">
            <% if policy(manage_group.group).edit? %>
              <div class="d-flex justify-content-end">
                <div class="dropstart">
                  <button class="btn " id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                    <h5>...</h5>
                  </button>
                  <ul class="dropdown-menu shadow-sm border-light">
                    <%= link_to "Edit", edit_group_path(manage_group.group), class: "dropdown-item" %>
                    <%= link_to 'Delete', group_path(manage_group.group), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "dropdown-item" %>
                  </ul>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @group_lists&.each do |group| %>
    <div class="card mt-3 shadow">
      <div class="card-body" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-2">
            <%= link_to group_path(group), class: "text-decoration-none text-dark" do %>
              <%= image_tag group.image.url, class: "img-thumbnail shadow-sm border-light", style: "width: 100%; height:100%" %>
            <% end %>
          </div>
          <div class="col-8">
            <p class="badge bg-light text-dark shadow-sm" style="font-size: min( 2vw, 12px)"><%= group.privacy.humanize %></p>
            <h3 style="font-size: min( 3vw, 20px)"><b><%= group.name %></b></h3>
            <p style="font-size: min( 2vw, 15px)"><%= group.description %></p>
          </div>
          <div class="col-2">
            <div class="d-flex justify-content-end">
              <%= link_to "Join", join_groups_path(group_id: group), data: { confirm: 'Are you sure you want to join this group?' }, class: "btn btn-light btn-sm px-3 shadow-sm", method: :post %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @requests&.each do |request| %>
    <div class="card mt-3 shadow">
      <div class="card-body" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-2">
            <%= link_to group_path(request.group), class: "text-decoration-none text-dark" do %>
              <%= image_tag request.group.image.url, class: "img-thumbnail shadow-sm border-light", style: "width: 100%; height:100%" %>
            <% end %>
          </div>
          <div class="col-8">
            <p class="badge bg-light text-dark shadow-sm" style="font-size: min( 2vw, 12px)"><%= request.group.privacy.humanize %></p>
            <h3 style="font-size: min( 3vw, 20px)"><b><%= request.group.name %></b></h3>
            <p style="font-size: min( 2vw, 15px)"><%= request.group.description %></p>
          </div>
          <div class="col-2">
            <div class="d-flex justify-content-end">
              <%= link_to "Cancel", join_group_cancel_path(request), data: { confirm: 'Are you sure you want to confirm this request?' }, class: "btn btn-light btn-sm px-2 shadow-sm", method: :put if request.may_cancel? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @joined_groups&.each do |joined_group| %>
    <div class="card mt-3 shadow">
      <div class="card-body" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-2">
            <%= link_to group_path(joined_group.group), class: "text-decoration-none text-dark" do %>
              <%= image_tag joined_group.group.image.url, class: "img-thumbnail shadow-sm border-light", style: "width: 100%; height:100%" %>
            <% end %>
          </div>
          <div class="col-8">
            <p class="badge bg-light text-dark shadow-sm" style="font-size: min( 2vw, 12px)"><%= joined_group.group.privacy.humanize %></p>
            <h3 style="font-size: min( 3vw, 20px)"><b><%= joined_group.group.name %></b></h3>
            <p style="font-size: min( 2vw, 15px)"><%= joined_group.group.description %></p>
          </div>
          <div class="col-2">
            <div class="d-flex justify-content-end">
              <%= link_to "Leave", join_group_leave_path(joined_group, @group), data: { confirm: 'Are you sure you want to approve this user?' }, class: "btn btn-light btn-sm px-2 shadow-sm mt-2", method: :put if joined_group.may_leave? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<%= render "shared_form/navbar" %>
<div class="container" style="margin-top: 100px">
  <h1><b>Create Group</b></h1>
  <div class="card w-100 mt-3 mb-5 shadow border-light">
    <div class="card-body bg-light">
      <%= form_for @group, url: groups_path, method: :post do |f| %>
        <div class="row mt-3">
          <%= render "form", f: f %>
          <div class="pt-1 text-center mb-2">
            <%= link_to 'Back', groups_path, class: "btn btn-warning px-5 mx-3 shadow-sm" %>
            <%= f.submit "Create", data: { confirm: 'Are you sure you want to create?' }, class: "btn btn-success px-5 mx-3 shadow-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<%= render "shared_form/navbar" %>
<div class="container justify-content-center" style="margin-top: 100px; margin-bottom: 100px; width: 75%;">
  <%= render "shared_error/flash_error" %>
  <div class="card shadow border-light bg-light ">
    <div class="rounded-start">
      <%= image_tag @group.image.url, class: "img-thumbnail shadow-sm border-light", style: "width: 100%; height:100%" %>
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-light shadow-sm" style="font-size: min( 1vw, 15px)">
      <%= link_to groups_path, class: "nav-link" do %>
          <i class="fa-solid fa-chevron-left"></i>
        <% end %>
      </span>
    </div>
    <div class="card-body" style="background-color: #e4ede4">
      <div class="row">
        <div class="col-sm-4">
          <h1 style="font-size: min( 3vw, 25px)"><b><%= @group.name %></b></h1>
          <p style="font-size: min( 1.5vw, 13px)"><b><%= @group.privacy.humanize %></b></p>
        </div>
        <div class="col-sm-8">
          <div class="d-flex justify-content-end mt-2">
            <%= link_to "Pending Posts", group_path(records: 'post'), class: "btn btn-light btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "#{JoinGroup.pending.where(group: @group).size} Approval", group_path(records: 'approvals'), class: "btn btn-light btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "#{JoinGroup.approved.where(group: @group).size} Members", group_path(records: 'members'), class: "btn btn-light btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
            <%= link_to "Assign Role", group_path(records: 'assign_role'), class: "btn btn-light btn-sm mt-2 px-2 shadow-sm mx-2", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% @approvals&.each do |approval| %>
    <div class="card mt-3 shadow">
      <div class="card-body" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-10">
            <h3 style="font-size: min( 2vw, 20px)"><b><%= approval.user.email %></b></h3>
            <%= content_tag :div, approval.updated_at.to_s(:long), class: "badge bg-light text-dark shadow-sm", style: "font-size: min( 1vw, 10px)" %>
          </div>
          <div class="col-2">
            <div class="d-flex justify-content-end">
              <%= link_to "Approve", join_group_approve_path(approval, @group), data: { confirm: 'Are you sure you want to approve this user?' }, class: "btn btn-light btn-sm px-2 shadow-sm mt-2", method: :put if approval.may_approve? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @members&.each do |member| %>
    <div class="card mt-3 shadow">
      <div class="card-body" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-8">
            <h3 style="font-size: min( 2vw, 20px)"><b><%= member.user.email %></b></h3>
            <%= content_tag :div, member.updated_at.to_s(:long), class: "badge bg-light text-dark shadow-sm", style: "font-size: min( 1vw, 10px)" %>
          </div>
          <div class="col-4">
            <div class="d-flex justify-content-end">
              <% if params[:records] == 'members' %>
                <%= link_to "Remove", join_group_remove_path(member, @group), data: { confirm: 'Are you sure you want to approve this user?' }, class: "btn btn-light btn-sm px-2 shadow-sm mt-2", method: :put if member.may_remove? %>
              <% else %>
                <%= form_for member, url: join_group_path(member, group_id: @group), method: :patch do |f| %>
                  <div class="input-group">
                  <%= f.select(:role, JoinGroup.roles.keys.map { |key| [key.humanize, key] }, { include_blank: "Role" }, { class: "form-control-sm form-select shadow-sm border-light", style: "font-size: min( 1vw, 18px)" }) %>
                  <%= f.submit "Assign", data: { confirm: 'Are you sure you want to assign role for this user?' }, class: "btn btn-sm btn-success shadow-sm", style: "font-size: min( 1vw, 18px)" %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>