config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts, except: :show do
    resources :comments, except: :show
  end
  resources :friendships, only: [:index, :create] do
    put :confirm, :unfriend, :ignore, :cancel
  end
  resources :groups
  resources :join_groups do
    put 'approve/:group_id', as: :approve, to: 'join_groups#approve'
    put :remove, :leave, :cancel
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'

  include AASM
  aasm column: :state do
    state :pending, initial: true
    state :confirmed, :unfriended, :cancelled, :ignored

    event :confirm do
      transitions from: :pending, to: :confirmed
    end

    event :unfriend do
      transitions from: :confirmed, to: :unfriended
    end

    event :cancel do
      transitions from: :pending, to: :cancelled
    end

    event :ignore do
      transitions from: :pending, to: :ignored
    end

    event :request do
      transitions from: [:unfriended, :cancelled, :ignored], to: :pending
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_friendship, only: [:confirm, :unfriend, :ignore, :cancel]

  def index
    friendships = current_user.friendships.where.not(state: not_friend_states).includes(:friend)
    inverse_friendships = current_user.inverse_friendships.where.not(state: not_friend_states).includes(:user)
    merge_ids = friendships.pluck(:friend_id) + inverse_friendships.pluck(:user_id) << current_user.id
    @users = User.where.not(id: merge_ids) if params[:records].blank? || params[:records] == 'add'
    @all_friends = friendships.confirmed + inverse_friendships.confirmed if params[:records] == 'all'
    @friend_requests = current_user.inverse_friendships.pending.order(id: :desc) if params[:records] == 'request'
    @sent_requests = current_user.friendships.pending.order(id: :desc) if params[:records] == 'sent'
  end

  def create
    check_friends_relation = current_user.friendships.find_by(friend_id: params[:friend_id])
    check_inverse_friends_relation = current_user.inverse_friendships.find_by(user_id: params[:friend_id])
    if update_friendship = current_user.friendships.where(state: not_friend_states).find_by(friend_id: params[:friend_id])
      update_friendship.request!
      flash[:notice] = "You successfully added"
      redirect_to friendships_path
    elsif check_friends_relation.blank? ||  check_inverse_friends_relation.blank? && current_user.id != params[:friend_id].to_i
      friendship = current_user.friendships.new(friend_id: params[:friend_id])
      if friendship.save
        flash[:notice] = "You successfully added"
        redirect_to friendships_path
      else
        flash[:alert] = friendship.errors.full_messages.join(', ')
      end
    else
      flash[:alert] = "You Can't Add this user again!"
      redirect_to friendships_path
    end
  end

  def confirm
    authorize @friendship, :confirm?, policy_class: FriendshipPolicy
    if @friendship.confirm!
      flash[:notice] = "Confirm Successfully"
    else
      flash[:alert] = @friendship.errors.full_messages.join(', ')
    end
    redirect_to friendships_path(records: :request)
  end

  def unfriend
    authorize @friendship, :unfriend?, policy_class: FriendshipPolicy
    if @friendship.unfriend!
      flash[:notice] = "Unfriend Successfully"
    else
      flash[:alert] = @friendship.errors.full_messages.join(', ')
    end
    redirect_to friendships_path(records: :all)
  end

  def ignore
    authorize @friendship, :ignore?, policy_class: FriendshipPolicy
    if @friendship.ignore!
      flash[:notice] = "Ignore Successfully"
    else
      flash[:alert] = @friendship.errors.full_messages.join(', ')
    end
    redirect_to friendships_path(records: :request)
  end

  def cancel
    authorize @friendship, :cancel?, policy_class: FriendshipPolicy
    if @friendship.cancel!
      flash[:notice] = "Cancel Successfully"
    else
      flash[:alert] = @friendship.errors.full_messages.join(', ')
    end
    redirect_to friendships_path(records: :sent)
  end

  private

  def set_friendship
    @friendship = Friendship.find(params[:friendship_id])
  end

  def not_friend_states
    [:unfriended, :ignored, :cancelled]
  end
end

app/views/friendships/index.html.erb
<%= render "shared_form/navbar" %>
<div class="container mb-5" style="margin-top: 120px">
  <%= render "shared_error/flash_error" %>
  <div class="card shadow" style="background-color: #e4ede4">
    <div class="card-body text-dark">
      <div class="d-flex justify-content-center">
        <%= link_to "Add Friends", friendships_path(records: 'add'), class: "btn btn-sm btn-light shadow-sm mx-4", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
        <%= link_to "All Friends", friendships_path(records: 'all'), class: "btn btn-sm btn-light shadow-sm mx-4", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
        <%= link_to "Friend Request", friendships_path(records: 'request'), class: "btn btn-sm btn-light shadow-sm mx-4", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
        <%= link_to "Sent Request", friendships_path(records: 'sent'), class: "btn btn-sm btn-light shadow-sm mx-4", style: "width: 130px; font-size: min( 1.5vw, 15px)" %>
      </div>
    </div>
  </div>
  <% @users&.each do |user| %>
    <div class="card mt-2 shadow border-light bg-body">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <b><%= user.email %></b>
          </div>
          <div class="col">
            <div class="d-flex justify-content-end">
              <%= link_to "Add", friendships_path(friend_id: user), data: { confirm: 'Are you sure you want to Add this user?' }, class: "btn btn-primary btn-sm px-3 shadow-sm", method: :post %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @all_friends&.each do |all_friend| %>
    <div class="card mt-2 shadow border-light bg-body">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <b><%= all_friend.friend.email if current_user == all_friend.user %></b>
            <b><%= all_friend.user.email if current_user == all_friend.friend %></b>
          </div>
          <div class="col">
            <div class="d-flex justify-content-end">
              <%= link_to "Unfriend", friendship_unfriend_path(all_friend), data: { confirm: 'Are you sure you want to unfriend? this user' }, class: "btn btn-danger btn-sm px-2 shadow-sm", method: :put if all_friend.may_unfriend? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @friend_requests&.each do |friendship| %>
    <div class="card mt-2 shadow border-light bg-body">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <b><%= friendship.friend.email if current_user == friendship.user %></b>
            <b><%= friendship.user.email if current_user == friendship.friend %></b>
          </div>
          <div class="col">
            <div class="d-flex justify-content-end">
              <%= link_to "Confirm", friendship_confirm_path(friendship), data: { confirm: 'Are you sure you want to confirm this request?' }, class: "btn btn-success btn-sm px-3 shadow-sm", method: :put if friendship.may_confirm? %>
              <%= link_to "Ignore", friendship_ignore_path(friendship), data: { confirm: 'Are you sure you want to ignore this request?' }, class: "btn btn-danger btn-sm px-3 mx-3 shadow-sm", method: :put if friendship.may_ignore? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% @sent_requests&.each do |friendship| %>
    <div class="card mt-2 shadow border-light bg-body">
      <div class="card-body">
        <div class="row">
          <div class="col">
            <b><%= friendship.friend.email if current_user == friendship.user %></b>
            <b><%= friendship.user.email if current_user == friendship.friend %></b>
          </div>
          <div class="col">
            <div class="d-flex justify-content-end">
              <%= link_to "Cancel", friendship_cancel_path(friendship), data: { confirm: 'Are you sure you want to cancel?' }, class: "btn btn-warning btn-sm px-3 shadow-sm", method: :put if friendship.may_cancel? %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>