config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts, except: :show do
    resources :comments, except: :show
  end
  resources :friendships, only: [:index, :create] do
    put :confirm, :unfriend, :ignore, :cancel
  end
  resources :groups
  resources :join_groups do
    put 'approve/:group_id', as: :approve, to: 'join_groups#approve'
    put :remove, :leave, :cancel
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, :genre, presence: true
  belongs_to :user
  has_many :comments

  mount_uploader :image, ImageUploader

  enum genre: [:to_all, :friends, :only_me]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy]
  include ApplicationHelper

  def index
    @posts = Post.where(id: filter_post).includes(:user, :comments).order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Successfully Created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    authorize @post, :edit?, policy_class: PostPolicy
  end

  def update
    authorize @post, :update?, policy_class: PostPolicy
    if @post.update(post_params)
      flash[:notice] = "Successfully Updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    authorize @post, :destroy?, policy_class: PostPolicy
    if @post.destroy
      flash[:notice] = "Successfully Deleted"
    else
      flash[:alert] = "Can't delete this post!"
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:image, :content, :genre)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_form.html.erb
<div class="col">
  <div class="form-outline mb-4">
    <%= f.text_area :content, class: "form-control shadow-sm", placeholder: "What's on your mind, #{current_user.email}?", :cols => 20, :rows => 1 %>
    <%= content_tag :p, @post.errors.full_messages_for(:content).join(', '), class: 'text-danger' if @post.errors.has_key?(:content) %>
    <%= f.select(:genre, Post.genres.keys.map { |key| [key.humanize, key] }, { :prompt => 'Privacy' }, class: "form-control form-select mt-3 shadow-sm") %>
    <%= content_tag :p, @post.errors.full_messages_for(:genre).join(', '), class: 'text-danger' if @post.errors.has_key?(:genre) %>
    <%= f.file_field :image, class: "form-control mt-3 mb-3 shadow-sm" %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "shared_form/navbar" %>
<div class="container" style="margin-top: 100px">
  <h1><b>Edit Post</b></h1>
  <div class="card w-100 mt-3 mb-5 shadow border-light">
    <div class="card-body bg-light">
      <%= form_for @post, url: post_path, method: :patch do |f| %>
        <div class="row mt-3">
          <%= render "form", f: f %>
          <div class="pt-1 text-center mb-2">
            <%= link_to 'Back', posts_path, class: "btn btn-warning px-5 mx-3 shadow-sm" %>
            <%= f.submit "Save", data: { confirm: 'Are you sure you want to save post?' }, class: "btn btn-success px-5 mx-3 shadow-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared_form/navbar" %>
<style>
    .btn:hover {
        background-color: transparent !important;
    }
</style>
<div class="container mb-5" style="margin-top: 120px">
  <%= render "shared_error/flash_error" %>
  <div class="card shadow" style="background-color: #e4ede4">
    <div class="card-body text-dark">
      <h1><b>Post</b></h1>
      <%= link_to new_post_path, class: "nav-link" do %>
        <div class="form-outline mb-4 text-center">
          <%= text_field_tag :p, nil, placeholder: "What's on your mind, #{current_user.email}?", readonly: :true, class: "form-control shadow-sm border-light" %>
        </div>
      <% end %>
    </div>
  </div>
  <% @posts.each do |post| %>
    <div class="card mt-3 shadow border-light">
      <div class="card-header shadow-sm border-light" style="background-color: #e4ede4">
        <div class="row">
          <div class="col-10">
            <h5 class="card-title mt-3" style="color:darkorange;"><b><%= post.user.email %></b></h5>
            <%= content_tag :div, post.created_at.to_s(:long), class: "badge bg-light text-dark shadow-sm" %>&nbsp;<%= content_tag :div, post.genre.humanize, class: "badge bg-secondary shadow-sm" %>
          </div>
          <% if policy(post).edit? %>
            <div class="col d-flex justify-content-end">
              <div class="dropstart">
                <button class="btn " id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                  <h5>...</h5>
                </button>
                <ul class="dropdown-menu shadow-sm border-light">
                  <%= link_to "Edit", edit_post_path(post), class: "dropdown-item" %>
                  <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "dropdown-item" %>
                </ul>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text mt-4 mb-4"><b></b> <%= post.content %></p>
        <% if post.image? %>
          <div class="overflow-hidden" style="width: 100%; aspect-ratio: 2/1">
            <%= image_tag post.image.url, style: "object-fit: cover" %>
          </div>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <%= link_to post_comments_path(post), class: "nav-link" do %>
          <% if post.comments.present? %>
            <p class="mt-2 mb-2"><%= post.comments.size %> Comments</p>
          <% else %>
            <p class="mt-2 mb-2">0 Comment</p>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "shared_form/navbar" %>
<div class="container" style="margin-top: 100px">
  <h1><b>Create Post</b></h1>
  <div class="card w-100 mt-3 mb-5 shadow border-light">
    <div class="card-body bg-light">
      <%= form_for @post, url: posts_path, method: :post do |f| %>
        <div class="row mt-3">
          <%= render "form", f: f %>
          <div class="pt-1 text-center mb-2">
            <%= link_to 'Back', posts_path, class: "btn btn-warning px-5 mx-3 shadow-sm" %>
            <%= f.submit "Post", data: { confirm: 'Are you sure you want to post?' }, class: "btn btn-success px-5 mx-3 shadow-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>